// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/test-bolt/pkg/models/shared"
	"net/http"
)

type AccountExistsRequest struct {
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey string `header:"style=simple,explode=false,name=X-Publishable-Key"`
	// A type and value combination that defines the identifier used to detect
	// the existence of an account.
	//
	Identifier shared.Identifier `queryParam:"style=form,explode=true,name=identifier"`
}

func (o *AccountExistsRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *AccountExistsRequest) GetIdentifier() shared.Identifier {
	if o == nil {
		return shared.Identifier{}
	}
	return o.Identifier
}

type AccountExistsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *AccountExistsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AccountExistsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AccountExistsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
