// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/test-bolt/pkg/models/shared"
	"net/http"
)

type GuestPaymentsInitializeRequest struct {
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey                     string                                     `header:"style=simple,explode=false,name=X-Publishable-Key"`
	GuestPaymentMethodInitializeRequest shared.GuestPaymentMethodInitializeRequest `request:"mediaType=application/json"`
}

func (o *GuestPaymentsInitializeRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *GuestPaymentsInitializeRequest) GetGuestPaymentMethodInitializeRequest() shared.GuestPaymentMethodInitializeRequest {
	if o == nil {
		return shared.GuestPaymentMethodInitializeRequest{}
	}
	return o.GuestPaymentMethodInitializeRequest
}

type GuestPaymentsInitializeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Payment token retrieved
	PaymentMethodInitializeResponse *shared.PaymentMethodInitializeResponse
}

func (o *GuestPaymentsInitializeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GuestPaymentsInitializeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GuestPaymentsInitializeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GuestPaymentsInitializeResponse) GetPaymentMethodInitializeResponse() *shared.PaymentMethodInitializeResponse {
	if o == nil {
		return nil
	}
	return o.PaymentMethodInitializeResponse
}
