// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/test-bolt/pkg/models/shared"
	"net/http"
)

type MerchantIdentifiersGetSecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (o *MerchantIdentifiersGetSecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

type MerchantIdentifiersGetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Identifiers were successfully retrieved
	Identifiers *shared.Identifiers
}

func (o *MerchantIdentifiersGetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MerchantIdentifiersGetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MerchantIdentifiersGetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MerchantIdentifiersGetResponse) GetIdentifiers() *shared.Identifiers {
	if o == nil {
		return nil
	}
	return o.Identifiers
}
