// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/test-bolt/pkg/models/shared"
	"net/http"
)

type PaymentsInitializeSecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
	Oauth  string `security:"scheme,type=oauth2,name=Authorization"`
}

func (o *PaymentsInitializeSecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *PaymentsInitializeSecurity) GetOauth() string {
	if o == nil {
		return ""
	}
	return o.Oauth
}

type PaymentsInitializeRequest struct {
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey                string                                `header:"style=simple,explode=false,name=X-Publishable-Key"`
	PaymentMethodInitializeRequest shared.PaymentMethodInitializeRequest `request:"mediaType=application/json"`
}

func (o *PaymentsInitializeRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *PaymentsInitializeRequest) GetPaymentMethodInitializeRequest() shared.PaymentMethodInitializeRequest {
	if o == nil {
		return shared.PaymentMethodInitializeRequest{}
	}
	return o.PaymentMethodInitializeRequest
}

type PaymentsInitializeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Payment token retrieved
	PaymentMethodInitializeResponse *shared.PaymentMethodInitializeResponse
}

func (o *PaymentsInitializeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PaymentsInitializeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PaymentsInitializeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PaymentsInitializeResponse) GetPaymentMethodInitializeResponse() *shared.PaymentMethodInitializeResponse {
	if o == nil {
		return nil
	}
	return o.PaymentMethodInitializeResponse
}
