// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/test-bolt/pkg/models/shared"
	"net/http"
)

type TestingAccountCreateSecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (o *TestingAccountCreateSecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

type TestingAccountCreateResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The account was successfully created
	AccountTestCreationData *shared.AccountTestCreationDataOutput
}

func (o *TestingAccountCreateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TestingAccountCreateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TestingAccountCreateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *TestingAccountCreateResponse) GetAccountTestCreationData() *shared.AccountTestCreationDataOutput {
	if o == nil {
		return nil
	}
	return o.AccountTestCreationData
}
