// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/speakeasy-sdks/test-bolt/pkg/models/shared"
)

type CallbackURLErrorInvalidURL struct {
	// The type of error returned
	DotTag shared.CallbackURLErrorInvalidURLTag `json:".tag"`
	// A human-readable error message, which might include information specific to
	// the request that was made.
	//
	Message string `json:"message"`
}

var _ error = &CallbackURLErrorInvalidURL{}

func (e *CallbackURLErrorInvalidURL) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
