// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// MerchantCallbacksUpdate400ApplicationJSON - The URL is invalid and cannot be set
type MerchantCallbacksUpdate400ApplicationJSON struct {
	RawResponse *http.Response `json:"-"`
}

var _ error = &MerchantCallbacksUpdate400ApplicationJSON{}

func (e *MerchantCallbacksUpdate400ApplicationJSON) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
