// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// MerchantCallbacksUpdateResponseBody - The URL is invalid and cannot be set
type MerchantCallbacksUpdateResponseBody struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &MerchantCallbacksUpdateResponseBody{}

func (e *MerchantCallbacksUpdateResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
