// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

type AccountTestCreationDataEmailState string

const (
	AccountTestCreationDataEmailStateMissing    AccountTestCreationDataEmailState = "missing"
	AccountTestCreationDataEmailStateUnverified AccountTestCreationDataEmailState = "unverified"
	AccountTestCreationDataEmailStateVerified   AccountTestCreationDataEmailState = "verified"
)

func (e AccountTestCreationDataEmailState) ToPointer() *AccountTestCreationDataEmailState {
	return &e
}

func (e *AccountTestCreationDataEmailState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "missing":
		fallthrough
	case "unverified":
		fallthrough
	case "verified":
		*e = AccountTestCreationDataEmailState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccountTestCreationDataEmailState: %v", v)
	}
}

type AccountTestCreationDataPhoneState string

const (
	AccountTestCreationDataPhoneStateMissing    AccountTestCreationDataPhoneState = "missing"
	AccountTestCreationDataPhoneStateUnverified AccountTestCreationDataPhoneState = "unverified"
	AccountTestCreationDataPhoneStateVerified   AccountTestCreationDataPhoneState = "verified"
)

func (e AccountTestCreationDataPhoneState) ToPointer() *AccountTestCreationDataPhoneState {
	return &e
}

func (e *AccountTestCreationDataPhoneState) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "missing":
		fallthrough
	case "unverified":
		fallthrough
	case "verified":
		*e = AccountTestCreationDataPhoneState(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccountTestCreationDataPhoneState: %v", v)
	}
}

type AccountTestCreationDataInput struct {
	DeactivateAt time.Time                         `json:"deactivate_at"`
	EmailState   AccountTestCreationDataEmailState `json:"email_state"`
	HasAddress   *bool                             `json:"has_address,omitempty"`
	IsMigrated   *bool                             `json:"is_migrated,omitempty"`
	PhoneState   AccountTestCreationDataPhoneState `json:"phone_state"`
}

func (o *AccountTestCreationDataInput) GetDeactivateAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.DeactivateAt
}

func (o *AccountTestCreationDataInput) GetEmailState() AccountTestCreationDataEmailState {
	if o == nil {
		return AccountTestCreationDataEmailState("")
	}
	return o.EmailState
}

func (o *AccountTestCreationDataInput) GetHasAddress() *bool {
	if o == nil {
		return nil
	}
	return o.HasAddress
}

func (o *AccountTestCreationDataInput) GetIsMigrated() *bool {
	if o == nil {
		return nil
	}
	return o.IsMigrated
}

func (o *AccountTestCreationDataInput) GetPhoneState() AccountTestCreationDataPhoneState {
	if o == nil {
		return AccountTestCreationDataPhoneState("")
	}
	return o.PhoneState
}

// AccountTestCreationDataOutput - The account was successfully created
type AccountTestCreationDataOutput struct {
	DeactivateAt time.Time                         `json:"deactivate_at"`
	Email        string                            `json:"email"`
	EmailState   AccountTestCreationDataEmailState `json:"email_state"`
	OauthCode    string                            `json:"oauth_code"`
	OtpCode      string                            `json:"otp_code"`
	Phone        string                            `json:"phone"`
	PhoneState   AccountTestCreationDataPhoneState `json:"phone_state"`
}

func (o *AccountTestCreationDataOutput) GetDeactivateAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.DeactivateAt
}

func (o *AccountTestCreationDataOutput) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *AccountTestCreationDataOutput) GetEmailState() AccountTestCreationDataEmailState {
	if o == nil {
		return AccountTestCreationDataEmailState("")
	}
	return o.EmailState
}

func (o *AccountTestCreationDataOutput) GetOauthCode() string {
	if o == nil {
		return ""
	}
	return o.OauthCode
}

func (o *AccountTestCreationDataOutput) GetOtpCode() string {
	if o == nil {
		return ""
	}
	return o.OtpCode
}

func (o *AccountTestCreationDataOutput) GetPhone() string {
	if o == nil {
		return ""
	}
	return o.Phone
}

func (o *AccountTestCreationDataOutput) GetPhoneState() AccountTestCreationDataPhoneState {
	if o == nil {
		return AccountTestCreationDataPhoneState("")
	}
	return o.PhoneState
}
