// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Account struct {
	Addresses      []AddressListing          `json:"addresses"`
	PaymentMethods []PaymentMethodCreditCard `json:"payment_methods"`
	Profile        *Profile                  `json:"profile,omitempty"`
}

func (o *Account) GetAddresses() []AddressListing {
	if o == nil {
		return []AddressListing{}
	}
	return o.Addresses
}

func (o *Account) GetPaymentMethods() []PaymentMethodCreditCard {
	if o == nil {
		return []PaymentMethodCreditCard{}
	}
	return o.PaymentMethods
}

func (o *Account) GetProfile() *Profile {
	if o == nil {
		return nil
	}
	return o.Profile
}
