// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AddressListing struct {
	Company        *string `json:"company,omitempty"`
	CountryCode    string  `json:"country_code"`
	Email          *string `json:"email,omitempty"`
	FirstName      string  `json:"first_name"`
	ID             string  `json:"id"`
	IsDefault      *bool   `json:"is_default,omitempty"`
	LastName       string  `json:"last_name"`
	Locality       string  `json:"locality"`
	Phone          *string `json:"phone,omitempty"`
	PostalCode     string  `json:"postal_code"`
	Region         *string `json:"region,omitempty"`
	StreetAddress1 string  `json:"street_address1"`
	StreetAddress2 *string `json:"street_address2,omitempty"`
}

func (o *AddressListing) GetCompany() *string {
	if o == nil {
		return nil
	}
	return o.Company
}

func (o *AddressListing) GetCountryCode() string {
	if o == nil {
		return ""
	}
	return o.CountryCode
}

func (o *AddressListing) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *AddressListing) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *AddressListing) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *AddressListing) GetIsDefault() *bool {
	if o == nil {
		return nil
	}
	return o.IsDefault
}

func (o *AddressListing) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *AddressListing) GetLocality() string {
	if o == nil {
		return ""
	}
	return o.Locality
}

func (o *AddressListing) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *AddressListing) GetPostalCode() string {
	if o == nil {
		return ""
	}
	return o.PostalCode
}

func (o *AddressListing) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *AddressListing) GetStreetAddress1() string {
	if o == nil {
		return ""
	}
	return o.StreetAddress1
}

func (o *AddressListing) GetStreetAddress2() *string {
	if o == nil {
		return nil
	}
	return o.StreetAddress2
}
