// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AddressReferenceExplicitTag - The type of address reference
type AddressReferenceExplicitTag string

const (
	AddressReferenceExplicitTagExplicit AddressReferenceExplicitTag = "explicit"
)

func (e AddressReferenceExplicitTag) ToPointer() *AddressReferenceExplicitTag {
	return &e
}

func (e *AddressReferenceExplicitTag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "explicit":
		*e = AddressReferenceExplicitTag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AddressReferenceExplicitTag: %v", v)
	}
}

type AddressReferenceExplicit struct {
	// The type of address reference
	DotTag         AddressReferenceExplicitTag `json:".tag"`
	Company        *string                     `json:"company,omitempty"`
	CountryCode    string                      `json:"country_code"`
	Email          *string                     `json:"email,omitempty"`
	FirstName      string                      `json:"first_name"`
	ID             string                      `json:"id"`
	LastName       string                      `json:"last_name"`
	Locality       string                      `json:"locality"`
	Phone          *string                     `json:"phone,omitempty"`
	PostalCode     string                      `json:"postal_code"`
	Region         *string                     `json:"region,omitempty"`
	StreetAddress1 string                      `json:"street_address1"`
	StreetAddress2 *string                     `json:"street_address2,omitempty"`
}

func (o *AddressReferenceExplicit) GetDotTag() AddressReferenceExplicitTag {
	if o == nil {
		return AddressReferenceExplicitTag("")
	}
	return o.DotTag
}

func (o *AddressReferenceExplicit) GetCompany() *string {
	if o == nil {
		return nil
	}
	return o.Company
}

func (o *AddressReferenceExplicit) GetCountryCode() string {
	if o == nil {
		return ""
	}
	return o.CountryCode
}

func (o *AddressReferenceExplicit) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *AddressReferenceExplicit) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *AddressReferenceExplicit) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *AddressReferenceExplicit) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *AddressReferenceExplicit) GetLocality() string {
	if o == nil {
		return ""
	}
	return o.Locality
}

func (o *AddressReferenceExplicit) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *AddressReferenceExplicit) GetPostalCode() string {
	if o == nil {
		return ""
	}
	return o.PostalCode
}

func (o *AddressReferenceExplicit) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *AddressReferenceExplicit) GetStreetAddress1() string {
	if o == nil {
		return ""
	}
	return o.StreetAddress1
}

func (o *AddressReferenceExplicit) GetStreetAddress2() *string {
	if o == nil {
		return nil
	}
	return o.StreetAddress2
}
