// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AddressErrorInvalidRegionTag - The type of error returned
type AddressErrorInvalidRegionTag string

const (
	AddressErrorInvalidRegionTagInvalidRegion AddressErrorInvalidRegionTag = "invalid_region"
)

func (e AddressErrorInvalidRegionTag) ToPointer() *AddressErrorInvalidRegionTag {
	return &e
}

func (e *AddressErrorInvalidRegionTag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "invalid_region":
		*e = AddressErrorInvalidRegionTag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AddressErrorInvalidRegionTag: %v", v)
	}
}

type AddressErrorInvalidRegion struct {
	// The type of error returned
	DotTag AddressErrorInvalidRegionTag `json:".tag"`
	// A human-readable error message, which might include information specific to
	// the request that was made.
	//
	Message string `json:"message"`
}

func (o *AddressErrorInvalidRegion) GetDotTag() AddressErrorInvalidRegionTag {
	if o == nil {
		return AddressErrorInvalidRegionTag("")
	}
	return o.DotTag
}

func (o *AddressErrorInvalidRegion) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
