// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/test-bolt/pkg/utils"
)

type AddressErrorInvalidPostalCode struct {
	// The type of error returned
	dotTag string `const:"invalid_postal_code" json:".tag"`
	// A human-readable error message, which might include information specific to
	// the request that was made.
	//
	Message string `json:"message"`
}

func (a AddressErrorInvalidPostalCode) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddressErrorInvalidPostalCode) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *AddressErrorInvalidPostalCode) GetDotTag() string {
	return "invalid_postal_code"
}

func (o *AddressErrorInvalidPostalCode) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
