// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/test-bolt/pkg/utils"
)

type AddressReferenceID struct {
	// The type of address reference
	dotTag string `const:"id" json:".tag"`
	// The address's ID
	ID string `json:"id"`
}

func (a AddressReferenceID) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddressReferenceID) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *AddressReferenceID) GetDotTag() string {
	return "id"
}

func (o *AddressReferenceID) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
