// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CallbackUrls - Callbacks URLs were successfully retrieved
type CallbackUrls struct {
	AccountPage                   *string `json:"account_page,omitempty"`
	BaseDomain                    *string `json:"base_domain,omitempty"`
	ConfirmationRedirect          *string `json:"confirmation_redirect,omitempty"`
	CreateOrder                   *string `json:"create_order,omitempty"`
	Debug                         *string `json:"debug,omitempty"`
	GetAccount                    *string `json:"get_account,omitempty"`
	MobileAppDomain               *string `json:"mobile_app_domain,omitempty"`
	OauthLogout                   *string `json:"oauth_logout,omitempty"`
	OauthRedirect                 *string `json:"oauth_redirect,omitempty"`
	PrivacyPolicy                 *string `json:"privacy_policy,omitempty"`
	ProductInfo                   *string `json:"product_info,omitempty"`
	RemoteAPI                     *string `json:"remote_api,omitempty"`
	Shipping                      *string `json:"shipping,omitempty"`
	SupportPage                   *string `json:"support_page,omitempty"`
	Tax                           *string `json:"tax,omitempty"`
	TermsOfService                *string `json:"terms_of_service,omitempty"`
	UniversalMerchantAPI          *string `json:"universal_merchant_api,omitempty"`
	UpdateCart                    *string `json:"update_cart,omitempty"`
	ValidateAdditionalAccountData *string `json:"validate_additional_account_data,omitempty"`
}

func (o *CallbackUrls) GetAccountPage() *string {
	if o == nil {
		return nil
	}
	return o.AccountPage
}

func (o *CallbackUrls) GetBaseDomain() *string {
	if o == nil {
		return nil
	}
	return o.BaseDomain
}

func (o *CallbackUrls) GetConfirmationRedirect() *string {
	if o == nil {
		return nil
	}
	return o.ConfirmationRedirect
}

func (o *CallbackUrls) GetCreateOrder() *string {
	if o == nil {
		return nil
	}
	return o.CreateOrder
}

func (o *CallbackUrls) GetDebug() *string {
	if o == nil {
		return nil
	}
	return o.Debug
}

func (o *CallbackUrls) GetGetAccount() *string {
	if o == nil {
		return nil
	}
	return o.GetAccount
}

func (o *CallbackUrls) GetMobileAppDomain() *string {
	if o == nil {
		return nil
	}
	return o.MobileAppDomain
}

func (o *CallbackUrls) GetOauthLogout() *string {
	if o == nil {
		return nil
	}
	return o.OauthLogout
}

func (o *CallbackUrls) GetOauthRedirect() *string {
	if o == nil {
		return nil
	}
	return o.OauthRedirect
}

func (o *CallbackUrls) GetPrivacyPolicy() *string {
	if o == nil {
		return nil
	}
	return o.PrivacyPolicy
}

func (o *CallbackUrls) GetProductInfo() *string {
	if o == nil {
		return nil
	}
	return o.ProductInfo
}

func (o *CallbackUrls) GetRemoteAPI() *string {
	if o == nil {
		return nil
	}
	return o.RemoteAPI
}

func (o *CallbackUrls) GetShipping() *string {
	if o == nil {
		return nil
	}
	return o.Shipping
}

func (o *CallbackUrls) GetSupportPage() *string {
	if o == nil {
		return nil
	}
	return o.SupportPage
}

func (o *CallbackUrls) GetTax() *string {
	if o == nil {
		return nil
	}
	return o.Tax
}

func (o *CallbackUrls) GetTermsOfService() *string {
	if o == nil {
		return nil
	}
	return o.TermsOfService
}

func (o *CallbackUrls) GetUniversalMerchantAPI() *string {
	if o == nil {
		return nil
	}
	return o.UniversalMerchantAPI
}

func (o *CallbackUrls) GetUpdateCart() *string {
	if o == nil {
		return nil
	}
	return o.UpdateCart
}

func (o *CallbackUrls) GetValidateAdditionalAccountData() *string {
	if o == nil {
		return nil
	}
	return o.ValidateAdditionalAccountData
}
