// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/test-bolt/pkg/utils"
)

type CallbackURLErrorInvalidURL struct {
	// The type of error returned
	dotTag string `const:"invalid_url" json:".tag"`
	// A human-readable error message, which might include information specific to
	// the request that was made.
	//
	Message string `json:"message"`
}

func (c CallbackURLErrorInvalidURL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CallbackURLErrorInvalidURL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *CallbackURLErrorInvalidURL) GetDotTag() string {
	return "invalid_url"
}

func (o *CallbackURLErrorInvalidURL) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
