// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CartShipment struct {
	Address *AddressReference `json:"address,omitempty"`
	// The name of the carrier selected.
	Carrier *string  `json:"carrier,omitempty"`
	Cost    *Amounts `json:"cost,omitempty"`
}

func (o *CartShipment) GetAddress() *AddressReference {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *CartShipment) GetAddressExplicit() *AddressReferenceExplicit {
	if v := o.GetAddress(); v != nil {
		return v.AddressReferenceExplicit
	}
	return nil
}

func (o *CartShipment) GetAddressID() *AddressReferenceIdentifier {
	if v := o.GetAddress(); v != nil {
		return v.AddressReferenceIdentifier
	}
	return nil
}

func (o *CartShipment) GetCarrier() *string {
	if o == nil {
		return nil
	}
	return o.Carrier
}

func (o *CartShipment) GetCost() *Amounts {
	if o == nil {
		return nil
	}
	return o.Cost
}
