// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CartItem struct {
	// A human-readable description of this cart item.
	Description *string `json:"description,omitempty"`
	// Used to provide a link to the image associated with the item.
	ImageURL *string `json:"image_url,omitempty"`
	// The name of a given item.
	Name string `json:"name"`
	// The number of units that comprise this cart item.
	Quantity int64 `json:"quantity"`
	// This value is used by Bolt as an external reference to a given item.
	Reference string `json:"reference"`
	// The total amount, in cents, of the item including its taxes if applicable.
	TotalAmount int64 `json:"total_amount"`
	// The price of one unit of the item; for example, the price of one pack of socks.
	UnitPrice int64 `json:"unit_price"`
}

func (o *CartItem) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CartItem) GetImageURL() *string {
	if o == nil {
		return nil
	}
	return o.ImageURL
}

func (o *CartItem) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CartItem) GetQuantity() int64 {
	if o == nil {
		return 0
	}
	return o.Quantity
}

func (o *CartItem) GetReference() string {
	if o == nil {
		return ""
	}
	return o.Reference
}

func (o *CartItem) GetTotalAmount() int64 {
	if o == nil {
		return 0
	}
	return o.TotalAmount
}

func (o *CartItem) GetUnitPrice() int64 {
	if o == nil {
		return 0
	}
	return o.UnitPrice
}
