// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Cart struct {
	Amounts   Amounts        `json:"amounts"`
	Discounts []CartDiscount `json:"discounts,omitempty"`
	// This field corresponds to the merchant's order reference associated with this Bolt transaction.
	DisplayID *string    `json:"display_id,omitempty"`
	Items     []CartItem `json:"items,omitempty"`
	// Used optionally to pass additional information like order numbers or other IDs as needed.
	OrderDescription *string `json:"order_description,omitempty"`
	// This value is used by Bolt as an external reference to a given order. This reference must be unique per successful transaction.
	OrderReference string         `json:"order_reference"`
	Shipments      []CartShipment `json:"shipments,omitempty"`
}

func (o *Cart) GetAmounts() Amounts {
	if o == nil {
		return Amounts{}
	}
	return o.Amounts
}

func (o *Cart) GetDiscounts() []CartDiscount {
	if o == nil {
		return nil
	}
	return o.Discounts
}

func (o *Cart) GetDisplayID() *string {
	if o == nil {
		return nil
	}
	return o.DisplayID
}

func (o *Cart) GetItems() []CartItem {
	if o == nil {
		return nil
	}
	return o.Items
}

func (o *Cart) GetOrderDescription() *string {
	if o == nil {
		return nil
	}
	return o.OrderDescription
}

func (o *Cart) GetOrderReference() string {
	if o == nil {
		return ""
	}
	return o.OrderReference
}

func (o *Cart) GetShipments() []CartShipment {
	if o == nil {
		return nil
	}
	return o.Shipments
}
