// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CartDiscount struct {
	Amounts Amounts `json:"amounts"`
	// Discount code.
	Code *string `json:"code,omitempty"`
	// Used to provide a link to additional details, such as a landing page, associated with the discount offering.
	DetailsURL *string `json:"details_url,omitempty"`
}

func (o *CartDiscount) GetAmounts() Amounts {
	if o == nil {
		return Amounts{}
	}
	return o.Amounts
}

func (o *CartDiscount) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *CartDiscount) GetDetailsURL() *string {
	if o == nil {
		return nil
	}
	return o.DetailsURL
}
