// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// CreditCardNetwork - The credit card network.
type CreditCardNetwork string

const (
	CreditCardNetworkVisa         CreditCardNetwork = "visa"
	CreditCardNetworkMastercard   CreditCardNetwork = "mastercard"
	CreditCardNetworkAmex         CreditCardNetwork = "amex"
	CreditCardNetworkDiscover     CreditCardNetwork = "discover"
	CreditCardNetworkJcb          CreditCardNetwork = "jcb"
	CreditCardNetworkUnionpay     CreditCardNetwork = "unionpay"
	CreditCardNetworkAlliancedata CreditCardNetwork = "alliancedata"
	CreditCardNetworkCitiplcc     CreditCardNetwork = "citiplcc"
)

func (e CreditCardNetwork) ToPointer() *CreditCardNetwork {
	return &e
}

func (e *CreditCardNetwork) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "visa":
		fallthrough
	case "mastercard":
		fallthrough
	case "amex":
		fallthrough
	case "discover":
		fallthrough
	case "jcb":
		fallthrough
	case "unionpay":
		fallthrough
	case "alliancedata":
		fallthrough
	case "citiplcc":
		*e = CreditCardNetwork(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreditCardNetwork: %v", v)
	}
}

// CreditCard - Successfully generated test credit card details
type CreditCard struct {
	// The Bank Identification Number for the credit card. This is typically the first 4-6 digits of the credit card number.
	Bin string `json:"bin"`
	// The expiration date of the credit card. TODO TO MAKE EXPIRATION REUSABLE
	Expiration string `json:"expiration"`
	// The last 4 digits of the credit card number.
	Last4 string `json:"last4"`
	// The credit card network.
	Network CreditCardNetwork `json:"network"`
	// The Bolt token associated to the credit card.
	Token string `json:"token"`
}

func (o *CreditCard) GetBin() string {
	if o == nil {
		return ""
	}
	return o.Bin
}

func (o *CreditCard) GetExpiration() string {
	if o == nil {
		return ""
	}
	return o.Expiration
}

func (o *CreditCard) GetLast4() string {
	if o == nil {
		return ""
	}
	return o.Last4
}

func (o *CreditCard) GetNetwork() CreditCardNetwork {
	if o == nil {
		return CreditCardNetwork("")
	}
	return o.Network
}

func (o *CreditCard) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}
