// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/test-bolt/pkg/utils"
)

type EventGroup struct {
	dotTag     string `const:"group" json:".tag"`
	eventGroup string `const:"all" json:"event_group"`
}

func (e EventGroup) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EventGroup) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *EventGroup) GetDotTag() string {
	return "group"
}

func (o *EventGroup) GetEventGroup() string {
	return "all"
}
