// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GuestPaymentMethodInitializeRequest struct {
	Cart          Cart                `json:"cart"`
	PaymentMethod PaymentMethodPaypal `json:"payment_method"`
}

func (o *GuestPaymentMethodInitializeRequest) GetCart() Cart {
	if o == nil {
		return Cart{}
	}
	return o.Cart
}

func (o *GuestPaymentMethodInitializeRequest) GetPaymentMethod() PaymentMethodPaypal {
	if o == nil {
		return PaymentMethodPaypal{}
	}
	return o.PaymentMethod
}
