// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// IdentifierIdentifierType - The type of identifier
type IdentifierIdentifierType string

const (
	IdentifierIdentifierTypeEmail       IdentifierIdentifierType = "email"
	IdentifierIdentifierTypeEmailSha256 IdentifierIdentifierType = "email_sha256"
)

func (e IdentifierIdentifierType) ToPointer() *IdentifierIdentifierType {
	return &e
}

func (e *IdentifierIdentifierType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "email":
		fallthrough
	case "email_sha256":
		*e = IdentifierIdentifierType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IdentifierIdentifierType: %v", v)
	}
}

type Identifier struct {
	// The type of identifier
	IdentifierType IdentifierIdentifierType `queryParam:"name=identifier_type"`
	// The value of the identifier. The value must be valid for the specified `identifier_type`
	IdentifierValue string `queryParam:"name=identifier_value"`
}

func (o *Identifier) GetIdentifierType() IdentifierIdentifierType {
	if o == nil {
		return IdentifierIdentifierType("")
	}
	return o.IdentifierType
}

func (o *Identifier) GetIdentifierValue() string {
	if o == nil {
		return ""
	}
	return o.IdentifierValue
}
