// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type IdentifiersMerchantDivisions struct {
	PublishableKey string `json:"publishable_key"`
}

func (o *IdentifiersMerchantDivisions) GetPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.PublishableKey
}

type Identifiers struct {
	MerchantDivisions []IdentifiersMerchantDivisions `json:"merchant_divisions"`
	MerchantID        string                         `json:"merchant_id"`
	SigningSecret     string                         `json:"signing_secret"`
}

func (o *Identifiers) GetMerchantDivisions() []IdentifiersMerchantDivisions {
	if o == nil {
		return []IdentifiersMerchantDivisions{}
	}
	return o.MerchantDivisions
}

func (o *Identifiers) GetMerchantID() string {
	if o == nil {
		return ""
	}
	return o.MerchantID
}

func (o *Identifiers) GetSigningSecret() string {
	if o == nil {
		return ""
	}
	return o.SigningSecret
}
