// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/test-bolt/pkg/utils"
)

type PaymentMethodSavedPaymentMethod struct {
	dotTag string `const:"saved_payment_method" json:".tag"`
	// Payment ID of the saved Bolt Payment method.
	ID string `json:"id"`
}

func (p PaymentMethodSavedPaymentMethod) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentMethodSavedPaymentMethod) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *PaymentMethodSavedPaymentMethod) GetDotTag() string {
	return "saved_payment_method"
}

func (o *PaymentMethodSavedPaymentMethod) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
