// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/test-bolt/pkg/utils"
)

// PaymentMethodCreditCardNetwork - The credit card network.
type PaymentMethodCreditCardNetwork string

const (
	PaymentMethodCreditCardNetworkVisa         PaymentMethodCreditCardNetwork = "visa"
	PaymentMethodCreditCardNetworkMastercard   PaymentMethodCreditCardNetwork = "mastercard"
	PaymentMethodCreditCardNetworkAmex         PaymentMethodCreditCardNetwork = "amex"
	PaymentMethodCreditCardNetworkDiscover     PaymentMethodCreditCardNetwork = "discover"
	PaymentMethodCreditCardNetworkJcb          PaymentMethodCreditCardNetwork = "jcb"
	PaymentMethodCreditCardNetworkUnionpay     PaymentMethodCreditCardNetwork = "unionpay"
	PaymentMethodCreditCardNetworkAlliancedata PaymentMethodCreditCardNetwork = "alliancedata"
	PaymentMethodCreditCardNetworkCitiplcc     PaymentMethodCreditCardNetwork = "citiplcc"
)

func (e PaymentMethodCreditCardNetwork) ToPointer() *PaymentMethodCreditCardNetwork {
	return &e
}

func (e *PaymentMethodCreditCardNetwork) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "visa":
		fallthrough
	case "mastercard":
		fallthrough
	case "amex":
		fallthrough
	case "discover":
		fallthrough
	case "jcb":
		fallthrough
	case "unionpay":
		fallthrough
	case "alliancedata":
		fallthrough
	case "citiplcc":
		*e = PaymentMethodCreditCardNetwork(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentMethodCreditCardNetwork: %v", v)
	}
}

// PaymentMethodCreditCardType - Credit card type
type PaymentMethodCreditCardType string

const (
	PaymentMethodCreditCardTypeCredit PaymentMethodCreditCardType = "credit"
	PaymentMethodCreditCardTypePlcc   PaymentMethodCreditCardType = "plcc"
)

func (e PaymentMethodCreditCardType) ToPointer() *PaymentMethodCreditCardType {
	return &e
}

func (e *PaymentMethodCreditCardType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "credit":
		fallthrough
	case "plcc":
		*e = PaymentMethodCreditCardType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentMethodCreditCardType: %v", v)
	}
}

type PaymentMethodCreditCard struct {
	dotTag         string           `const:"credit_card" json:".tag"`
	BillingAddress AddressReference `json:"billing_address"`
	// The Bank Identification Number for the credit card. This is typically the first 4-6 digits of the credit card number.
	Bin string `json:"bin"`
	// The expiration date of the credit card. TODO TO MAKE EXPIRATION REUSABLE
	Expiration string  `json:"expiration"`
	ID         *string `json:"id,omitempty"`
	// The last 4 digits of the credit card number.
	Last4 string `json:"last4"`
	// The credit card network.
	Network PaymentMethodCreditCardNetwork `json:"network"`
	// The Bolt token associated to the credit card.
	Token string `json:"token"`
	// Credit card type
	Type PaymentMethodCreditCardType `json:"type"`
}

func (p PaymentMethodCreditCard) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentMethodCreditCard) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PaymentMethodCreditCard) GetDotTag() string {
	return "credit_card"
}

func (o *PaymentMethodCreditCard) GetBillingAddress() AddressReference {
	if o == nil {
		return AddressReference{}
	}
	return o.BillingAddress
}

func (o *PaymentMethodCreditCard) GetBillingAddressExplicit() *AddressReferenceExplicit {
	return o.GetBillingAddress().AddressReferenceExplicit
}

func (o *PaymentMethodCreditCard) GetBillingAddressID() *AddressReferenceID {
	return o.GetBillingAddress().AddressReferenceID
}

func (o *PaymentMethodCreditCard) GetBin() string {
	if o == nil {
		return ""
	}
	return o.Bin
}

func (o *PaymentMethodCreditCard) GetExpiration() string {
	if o == nil {
		return ""
	}
	return o.Expiration
}

func (o *PaymentMethodCreditCard) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PaymentMethodCreditCard) GetLast4() string {
	if o == nil {
		return ""
	}
	return o.Last4
}

func (o *PaymentMethodCreditCard) GetNetwork() PaymentMethodCreditCardNetwork {
	if o == nil {
		return PaymentMethodCreditCardNetwork("")
	}
	return o.Network
}

func (o *PaymentMethodCreditCard) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

func (o *PaymentMethodCreditCard) GetType() PaymentMethodCreditCardType {
	if o == nil {
		return PaymentMethodCreditCardType("")
	}
	return o.Type
}
