// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaymentMethodInitializeRequest struct {
	Cart          Cart                            `json:"cart"`
	PaymentMethod PaymentMethodSavedPaymentMethod `json:"payment_method"`
}

func (o *PaymentMethodInitializeRequest) GetCart() Cart {
	if o == nil {
		return Cart{}
	}
	return o.Cart
}

func (o *PaymentMethodInitializeRequest) GetPaymentMethod() PaymentMethodSavedPaymentMethod {
	if o == nil {
		return PaymentMethodSavedPaymentMethod{}
	}
	return o.PaymentMethod
}
