// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
)

type PaymentMethodInitializeRequestPaymentMethodType string

const (
	PaymentMethodInitializeRequestPaymentMethodTypePaymentMethodSavedPaymentMethod PaymentMethodInitializeRequestPaymentMethodType = "payment-method-saved-payment-method"
)

type PaymentMethodInitializeRequestPaymentMethod struct {
	PaymentMethodSavedPaymentMethod *PaymentMethodSavedPaymentMethod

	Type PaymentMethodInitializeRequestPaymentMethodType
}

func CreatePaymentMethodInitializeRequestPaymentMethodPaymentMethodSavedPaymentMethod(paymentMethodSavedPaymentMethod PaymentMethodSavedPaymentMethod) PaymentMethodInitializeRequestPaymentMethod {
	typ := PaymentMethodInitializeRequestPaymentMethodTypePaymentMethodSavedPaymentMethod

	return PaymentMethodInitializeRequestPaymentMethod{
		PaymentMethodSavedPaymentMethod: &paymentMethodSavedPaymentMethod,
		Type:                            typ,
	}
}

func (u *PaymentMethodInitializeRequestPaymentMethod) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	paymentMethodSavedPaymentMethod := new(PaymentMethodSavedPaymentMethod)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&paymentMethodSavedPaymentMethod); err == nil {
		u.PaymentMethodSavedPaymentMethod = paymentMethodSavedPaymentMethod
		u.Type = PaymentMethodInitializeRequestPaymentMethodTypePaymentMethodSavedPaymentMethod
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u PaymentMethodInitializeRequestPaymentMethod) MarshalJSON() ([]byte, error) {
	if u.PaymentMethodSavedPaymentMethod != nil {
		return json.Marshal(u.PaymentMethodSavedPaymentMethod)
	}

	return nil, nil
}

type PaymentMethodInitializeRequest struct {
	Cart          Cart                                        `json:"cart"`
	PaymentMethod PaymentMethodInitializeRequestPaymentMethod `json:"payment_method"`
}

func (o *PaymentMethodInitializeRequest) GetCart() Cart {
	if o == nil {
		return Cart{}
	}
	return o.Cart
}

func (o *PaymentMethodInitializeRequest) GetPaymentMethod() PaymentMethodInitializeRequestPaymentMethod {
	if o == nil {
		return PaymentMethodInitializeRequestPaymentMethod{}
	}
	return o.PaymentMethod
}
