// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Profile struct {
	// An email address.
	Email *string `json:"email,omitempty"`
	// The given name of the person associated with this record.
	FirstName *string `json:"first_name,omitempty"`
	// The last name of the person associated with this record.
	LastName *string `json:"last_name,omitempty"`
	// A phone number following E164 standards, in its globalized format, i.e. prepended with a plus sign.
	Phone *string `json:"phone,omitempty"`
}

func (o *Profile) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *Profile) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *Profile) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *Profile) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}
