// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/test-bolt/pkg/utils"
	"time"
)

// ShipmentTrackingUpdateStatus - The shipment's status.
type ShipmentTrackingUpdateStatus string

const (
	ShipmentTrackingUpdateStatusInTransit ShipmentTrackingUpdateStatus = "in_transit"
	ShipmentTrackingUpdateStatusCancelled ShipmentTrackingUpdateStatus = "cancelled"
	ShipmentTrackingUpdateStatusFailure   ShipmentTrackingUpdateStatus = "failure"
	ShipmentTrackingUpdateStatusDelivered ShipmentTrackingUpdateStatus = "delivered"
)

func (e ShipmentTrackingUpdateStatus) ToPointer() *ShipmentTrackingUpdateStatus {
	return &e
}

func (e *ShipmentTrackingUpdateStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "in_transit":
		fallthrough
	case "cancelled":
		fallthrough
	case "failure":
		fallthrough
	case "delivered":
		*e = ShipmentTrackingUpdateStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ShipmentTrackingUpdateStatus: %v", v)
	}
}

type ShipmentTrackingUpdateSchemasStatus string

const (
	ShipmentTrackingUpdateSchemasStatusUnknown            ShipmentTrackingUpdateSchemasStatus = "unknown"
	ShipmentTrackingUpdateSchemasStatusPreTransit         ShipmentTrackingUpdateSchemasStatus = "pre_transit"
	ShipmentTrackingUpdateSchemasStatusInTransit          ShipmentTrackingUpdateSchemasStatus = "in_transit"
	ShipmentTrackingUpdateSchemasStatusOutForDelivery     ShipmentTrackingUpdateSchemasStatus = "out_for_delivery"
	ShipmentTrackingUpdateSchemasStatusDelivered          ShipmentTrackingUpdateSchemasStatus = "delivered"
	ShipmentTrackingUpdateSchemasStatusAvailableForPickup ShipmentTrackingUpdateSchemasStatus = "available_for_pickup"
	ShipmentTrackingUpdateSchemasStatusReturnToSender     ShipmentTrackingUpdateSchemasStatus = "return_to_sender"
	ShipmentTrackingUpdateSchemasStatusFailure            ShipmentTrackingUpdateSchemasStatus = "failure"
	ShipmentTrackingUpdateSchemasStatusCancelled          ShipmentTrackingUpdateSchemasStatus = "cancelled"
	ShipmentTrackingUpdateSchemasStatusError              ShipmentTrackingUpdateSchemasStatus = "error"
)

func (e ShipmentTrackingUpdateSchemasStatus) ToPointer() *ShipmentTrackingUpdateSchemasStatus {
	return &e
}

func (e *ShipmentTrackingUpdateSchemasStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "unknown":
		fallthrough
	case "pre_transit":
		fallthrough
	case "in_transit":
		fallthrough
	case "out_for_delivery":
		fallthrough
	case "delivered":
		fallthrough
	case "available_for_pickup":
		fallthrough
	case "return_to_sender":
		fallthrough
	case "failure":
		fallthrough
	case "cancelled":
		fallthrough
	case "error":
		*e = ShipmentTrackingUpdateSchemasStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ShipmentTrackingUpdateSchemasStatus: %v", v)
	}
}

type TrackingDetails struct {
	// The country associated this this set of tracking details, if any.
	CountryCode *string `json:"country_code,omitempty"`
	// The tracking detail's timestamp.
	EventDate *string `json:"event_date,omitempty"`
	// The locality associated this this set of tracking details, if any.
	Locality *string `json:"locality,omitempty"`
	// An arbitrary, human-readable message associated with this set of tracking details.
	Message *string `json:"message,omitempty"`
	// The postal associated this this set of tracking details, if any.
	PostalCode *string `json:"postal_code,omitempty"`
	// The region associated this this set of tracking details, if any.
	Region *string                              `json:"region,omitempty"`
	Status *ShipmentTrackingUpdateSchemasStatus `json:"status,omitempty"`
}

func (o *TrackingDetails) GetCountryCode() *string {
	if o == nil {
		return nil
	}
	return o.CountryCode
}

func (o *TrackingDetails) GetEventDate() *string {
	if o == nil {
		return nil
	}
	return o.EventDate
}

func (o *TrackingDetails) GetLocality() *string {
	if o == nil {
		return nil
	}
	return o.Locality
}

func (o *TrackingDetails) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *TrackingDetails) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

func (o *TrackingDetails) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *TrackingDetails) GetStatus() *ShipmentTrackingUpdateSchemasStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

type ShipmentTrackingUpdate struct {
	// The shipment's actual or estimated delivery date.
	DeliveryDate *time.Time `json:"delivery_date,omitempty"`
	// The shipment's status.
	Status ShipmentTrackingUpdateStatus `json:"status"`
	// A list of tracking updates that contain the shipment's status, location, and any unique messages.
	TrackingDetails []TrackingDetails `json:"tracking_details"`
	// The carrier's tracking number for the shipment. Must be prefixed with `MockBolt`.
	TrackingNumber string `json:"tracking_number"`
}

func (s ShipmentTrackingUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ShipmentTrackingUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ShipmentTrackingUpdate) GetDeliveryDate() *time.Time {
	if o == nil {
		return nil
	}
	return o.DeliveryDate
}

func (o *ShipmentTrackingUpdate) GetStatus() ShipmentTrackingUpdateStatus {
	if o == nil {
		return ShipmentTrackingUpdateStatus("")
	}
	return o.Status
}

func (o *ShipmentTrackingUpdate) GetTrackingDetails() []TrackingDetails {
	if o == nil {
		return []TrackingDetails{}
	}
	return o.TrackingDetails
}

func (o *ShipmentTrackingUpdate) GetTrackingNumber() string {
	if o == nil {
		return ""
	}
	return o.TrackingNumber
}
