// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package callbacks

import (
	"net/http"
)

type WebhooksCreateWebhookEventResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func (o *WebhooksCreateWebhookEventResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *WebhooksCreateWebhookEventResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *WebhooksCreateWebhookEventResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

type WebhooksCreateWebhookEventRequestBody struct {
	Message string `json:"message"`
}

func (o *WebhooksCreateWebhookEventRequestBody) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
